### ISSUE TITLE
When will be available for ubuntu ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [langchain-ai/langgraph-studio#89] opened 2024-08-21 08:45 UTC
When will be available for ubuntu ?

**Comment by dqbd** [comment] 2024-08-21 15:12
Hello @hemangjoshi37a! Linux support is currently not planned at the moment, but you can use the CLI in the interim https://langchain-ai.github.io/langgraph/cloud/reference/cli/.

**Comment by gitgud5000** [comment] 2024-08-21 16:41
Hey @dqbd  and team,

It would be awesome to have an alternative for non-Mac users. A web server solution for Ubuntu would be great and could work well for both Windows and Ubuntu developers.

By the way, I’ve been using the CLI and managed to get it working. Thanks for the great work!

**Comment by hemangjoshi37a** [comment] 2024-08-22 04:11
I have been using https://github.com/microsoft/autogen/tree/main/samples/apps/autogen-studio which works great with Linux and great alternative to this repo.

**Comment by filipefmelo** [comment] 2024-08-23 09:35
I know it's probably been asked before but I'll ask again, just to reiterate and further concentrate your attention in non Mac users. Please release a Windows (or Web) version :)

**Comment by dqbd** [comment] 2024-08-26 12:17
Closing as duplicate of #23

**Closed by dqbd** 2024-08-26 12:17 UTC
Labels: enhancement

**Comment by hinthornw** [comment] 2024-11-21 02:09
Hi all! As mentioned in the [other thread](https://github.com/langchain-ai/langgraph-studio/issues/63#issuecomment-2489918221) and ([in the docs](https://langchain-ai.github.io/langgraph/how-tos/local-studio/), we now support a similar experience using the:

```shell
langgraph dev
```
command.

We don't have near-term plans to develop a desktop application for linux; instead we want to ensure we support the same functionality through the CLI + web UI.
